version: '3.1'
services:
  stats-server:
    build: statisticservice/
    image: alexeypracticum/ewm-statistics
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewmstatistics
      - DB_NAME=ewmstatistics
      - POSTGRES_USER=alex
      - POSTGRES_PASSWORD=alex

  stats-db:
    image: postgres:14-alpine
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_DB=ewmstatistics
      - POSTGRES_USER=alex
      - POSTGRES_PASSWORD=alex

  ewm-service:
    build: mainservice/
    image: alexeypracticum/ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - ewm-db
    environment:
      - STATS_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewmmainservice
      - DB_NAME=ewmmainservice
      - POSTGRES_USER=alex
      - POSTGRES_PASSWORD=alex

  ewm-db:
    image: postgres:14-alpine
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewmmainservice
      - POSTGRES_USER=alex
      - POSTGRES_PASSWORD=alex